pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'PaperMC'
			url = 'https://repo.papermc.io/repository/maven-public/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// Should match your modid
rootProject.name = 'sign-edit'

include ':sign-edit-paper'
project(':sign-edit-paper').projectDir = file('server')
